name: PNR Status Watcher

on:
  schedule:
    - cron: "0,30 1-18 * * *"
  workflow_dispatch:

jobs:
  check-pnr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run PNR watcher
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python pnr_watcher.py


      - name: Commit status file if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add last_status.txt
          git commit -m "Update PNR status" || echo "No changes"
          git push
